Tildes y tipos arreglados en el pull request
Jacobo722/hyperblog pull request #1
Opened 2022-10-04 20:30 UTC by Jacobo722

No debimos pasar este error a master

2022-10-04 20:39 UTC, moises6661 requested changes
En ves de usar tildes directas usa entidades html.

2022-10-04 20:51 UTC, Jacobo722 commented
Cambios hechos porfavor hazme el merge

2022-10-04 20:57 UTC, moises6661 approved these changes

2022-10-04 20:59 UTC, merged

2022-10-04 21:03 UTC, Jacobo722 commented
Gracias moises por hacer el merge de fix-Type con el master. y que bueno que borrastes la rama fix-Type pues era solo para arreglar las tildes.

2022-10-05 06:49 UTC, moises6661 commented
de nada jefe